os:
  - linux

language: python

python:
  - "3.5"
  - "3.6"
  
install:
  - "sudo apt-get install libdb5.3-dev"
  - "pip install pip setuptools --upgrade"
  - "pip install tox-travis"

script: 
  - tox
